# Generated by Django 3.0.6 on 2020-05-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=16, unique=True, verbose_name='电话/用户号')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
