# Generated by Django 3.0.6 on 2020-05-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcemetnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=16, unique=True, verbose_name='公告标题')),
                ('a_content', models.CharField(max_length=255, null=True, verbose_name='公告内容')),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_name', models.CharField(max_length=16, unique=True, verbose_name='类别')),
            ],
            options={
                'db_table': 'kind',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_uid', models.CharField(max_length=16, verbose_name='帖子所属的用户id')),
                ('t_kind', models.CharField(max_length=16, verbose_name='帖子类型')),
                ('t_photo', models.CharField(max_length=128, null=True, verbose_name='帖子图片')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('t_content', models.CharField(max_length=255, verbose_name='帖子正文')),
                ('t_title', models.CharField(max_length=64, verbose_name='帖子标题')),
                ('t_introduce', models.CharField(max_length=255, verbose_name='帖子简介')),
                ('recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
            ],
        ),
    ]
