# Generated by Django 3.0.6 on 2020-05-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_announcemetnt_kind_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcemetnt',
            new_name='Announcement',
        ),
    ]
