# Generated by Django 3.0.6 on 2020-05-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200526_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_tid', models.CharField(max_length=16, verbose_name='帖子ID')),
                ('r_uid', models.CharField(max_length=16, verbose_name='留言者')),
                ('r_content', models.CharField(max_length=255, verbose_name='留言内容')),
                ('r_photo', models.CharField(max_length=128, null=True, verbose_name='图片')),
                ('r_time', models.DateField(auto_now_add=True, verbose_name='留言时间')),
            ],
            options={
                'db_table': 'reply',
            },
        ),
    ]
